version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:3.1.2
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run: 
          name: Download AppMap Binaries
          command: |
            curl -O https://github.com/getappmap/appmap-js/releases/download/%40appland%2Fappmap-v3.112.0/appmap-linux-x64
            chmod +x appmap-linux-x64
            sudo mv appmap-linux-x64 /usr/local/bin/appmap
      - run:
          name: Install AppMap
          command: |
            appmap install --no-interactive --no-overwrite-appmap-config
      - run:
          name: Database setup
          command: bin/rails db:migrate
      - run:
          name: Run tests
          command: bin/rails test
