version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  aws-s3: circleci/aws-s3@4.0.0
  aws-cli: circleci/aws-cli@4.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

    steps:
      - checkout
      - ruby/install-deps

      - run:
          name: Database setup
          command: bin/rails db:migrate
      - run:
          name: Run tests
          command: bin/rails test

      - run:
          name: Create archive of AppMaps
          command: tar --remove-files -cvzf <<pipeline.git.revision>>.tar tmp/appmap/

      - aws-cli/setup:
          profile_name: Circle-CI-Write-to-S3
          role_arn: arn:aws:iam::823624377950:role/Circle-CI-Write-to-S3
      
      - aws-s3/copy:
          from: <<pipeline.git.revision>>.tar
          profile_name: Circle-CI-Write-to-S3
          to: s3://circleci-appmaps/
          arguments: --region us-west-2


      

  run_appmap_analysis:
    docker:
      - image: cimg/ruby:3.1.2

    steps:
      - checkout

      - run:
          name: Get base Git SHA
          command: echo 'export BASE_SHA=$(git merge-base origin/main $CIRCLE_BRANCH)' >> $BASH_ENV

      - run:
          name: Run AppMap Analysis
          command: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $GITHUB_PAT" \
              -H "Content-Type: application/json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/land-of-apps/rails-7-app/dispatches \
              -d @- \<<EOF 
            {
              "event_type": "run_appmap_analysis",
              "client_payload": {
                "base_sha": "$BASE_SHA",
                "head_sha": "<< pipeline.git.revision >>"
              }
            }
            EOF

workflows:
  build:
    jobs:
      - build
      - run_appmap_analysis:
           filters:
            branches:
              ignore:
                - main
