name: issue32-test

on:
  push:
    branches:
    - issue32-test


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Rails test setup
        run: ./bin/rails db:migrate
      - name: Run tests
        run: ./bin/rails test

      - name: Install AppMap tools
        uses: getappmap/install-action@v1
        with:
          install-appmap-library: false

      - name: Archive AppMaps
        uses: getappmap/archive-action@v1
        with:
          directory: .
      
      - name: Check Rate Limit
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/rate_limit
      
      - name: Check Authenticated GitHub API Rate Limit
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/rate_limit


      - name: Analyze AppMaps
        uses: getappmap/analyze-action@v1
        with:
          directory: .
          base-revision: 57580894e2d453b34ca77eb95c4e466e72375ed3
          head-revision: 8dfc876e7eb1923f8cfaaa6df212efeea8f598b3

      - name: Check Rate Limit
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/rate_limit
      
      - name: Check Authenticated GitHub API Rate Limit
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/rate_limit