name: Dump GH Context

on:
  pull_request:
    branches:
      - pc/testing-gh-actions
  push:
    branches:
      - pc/testing-gh-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"